/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com

import 'package:flutter/material.dart';

class DesignColors {
  static const Color primaryColor = Color(0xFF1E3490);
  static const Color secondaryColor = Color(0xFF1E3490);
  static const Color errorColor = Colors.red;
  static const Color secondaryBackgroundColor = Color(0xFFF3F3F3);
  static const Color grey = Color(0xFFB4B9C5);
  static const Color textColor = Color(0xFF333333);
  static const Color white = Color(0xFFFFFFFF);
  static const Color yellow1 = Color(0xFFFCF6CC);
  static const Color yellow2 = Color(0xFFF1D302);
  static const Color yellow3 = Color(0xFFFFC73C);
  static const Color black = Color(0xFF000000);
  static const Color lightBlack = Color(0xFF2C2C2C);
  static const Color red = Color(0xFFFA441C);
  static const Color lightGreen = Color(0xFFC5EBC9);
  static const Color gray1 = Color(0xFFD2D6E9);
  static const Color gray2 = Color(0xFFD9D9D9);
  static const Color gray3 = Color(0xFF9F9F9F);
  static const Color gray4 = Color(0xFFf0f1f6);
  static const Color gray = Color(0xFFf3f3f3);

  static const MaterialColor goldPrimarySwatch = MaterialColor(
    0xFF1E3490,
    <int, Color>{
      50: Color(0xFF1E3490),
      100: Color(0xFF1E3490),
      200: Color(0xFF1E3490),
      300: Color(0xFF1E3490),
      400: Color(0xFF1E3490),
      500: Color(0xFF1E3490),
      600: Color(0xFF1E3490),
      700: Color(0xFF1E3490),
      800: Color(0xFF1E3490),
      900: Color(0xFF1E3490),
    },
  );
  static const MaterialColor whitePrimarySwatch = MaterialColor(
    0xFFFFFFFF,
    <int, Color>{
      50: Color(0xFFFFFFFF),
      100: Color(0xFFFFFFFF),
      200: Color(0xFFFFFFFF),
      300: Color(0xFFFFFFFF),
      400: Color(0xFFFFFFFF),
      500: Color(0xFFFFFFFF),
      600: Color(0xFFFFFFFF),
      700: Color(0xFFFFFFFF),
      800: Color(0xFFFFFFFF),
      900: Color(0xFFFFFFFF),
    },
  );
}
